[package]
name = "qrdecode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.9"
qrcodegen = "1.8.0"
qrcodegen-image = "1.3.0"
quircs = "0.10.2"
